#pragma once

#include "NativeGameplayTags.h"

namespace CombatGameplayTags
{
	// --- State Tags ---
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Attacking);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Countering);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Dodging);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Stunned);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Dead);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Blocking);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Running);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Boosting);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Weapon_InHand);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Weapon_Aiming);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Weapon_InFlight);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Weapon_Returning);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Warp_Locked);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Warp_Warping);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Projectile_Charging);

	// --- Ability Tags ---
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Melee_Light);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Melee_Heavy);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Counter);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dodge);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WarpStrike);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WeaponThrow);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WeaponRecall);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ProjectileShot);

	// --- Event Tags ---
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Hit);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Kill);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Counter);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_LastHit);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Weapon_Thrown);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Weapon_Caught);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Warp_Started);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Warp_Landed);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Projectile_Hit);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Boost_Activated);

	// --- Effect Tags ---
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Damage);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Stun);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Knockback);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Boost);

	// --- Invincibility / Hit React ---
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Invincible);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_HitReact);

	// --- GameplayCue Tags ---
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Combat_HitImpact);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Combat_WeaponTrail);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Combat_DodgeTrail);

	// --- Enemy AI Tags ---
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_State_Idle);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_State_Strafing);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_State_Approaching);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_State_Attacking);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_State_Retreating);
	AAACHARACTERCOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_State_PreparingAttack);
}
